// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0dph3P2JnQcFJrJa3ndScPQIUcOYnTd4',
    appId: '1:1011622911746:web:2bc47a9a958db43f8a6c1b',
    messagingSenderId: '1011622911746',
    projectId: 'habitflow-b4dcf',
    authDomain: 'habitflow-b4dcf.firebaseapp.com',
    storageBucket: 'habitflow-b4dcf.firebasestorage.app',
    measurementId: 'G-KVVJ4LEJ07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTYgxxKrp38Qs608wohsGb-2tQJXGIKVY',
    appId: '1:1011622911746:android:11f93aeaf3799af08a6c1b',
    messagingSenderId: '1011622911746',
    projectId: 'habitflow-b4dcf',
    storageBucket: 'habitflow-b4dcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOoJbWVh8zoVUZlVyZQ7-XVdWWFMyPWow',
    appId: '1:1011622911746:ios:5dd73c6cf808d3028a6c1b',
    messagingSenderId: '1011622911746',
    projectId: 'habitflow-b4dcf',
    storageBucket: 'habitflow-b4dcf.firebasestorage.app',
    iosBundleId: 'com.example.habitflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOoJbWVh8zoVUZlVyZQ7-XVdWWFMyPWow',
    appId: '1:1011622911746:ios:5dd73c6cf808d3028a6c1b',
    messagingSenderId: '1011622911746',
    projectId: 'habitflow-b4dcf',
    storageBucket: 'habitflow-b4dcf.firebasestorage.app',
    iosBundleId: 'com.example.habitflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0dph3P2JnQcFJrJa3ndScPQIUcOYnTd4',
    appId: '1:1011622911746:web:06bcc584fb0187468a6c1b',
    messagingSenderId: '1011622911746',
    projectId: 'habitflow-b4dcf',
    authDomain: 'habitflow-b4dcf.firebaseapp.com',
    storageBucket: 'habitflow-b4dcf.firebasestorage.app',
    measurementId: 'G-XSG62MVF3S',
  );
}
