name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Get Flutter dependencies
        working-directory: ./habitflow   # ← Important: point to subfolder
        run: flutter pub get

      - name: Setup Firebase
        working-directory: ./habitflow
        run: |
          flutter pub global activate flutterfire_cli
          echo "y" | flutterfire configure --project=$FIREBASE_PROJECT_ID --token=$FIREBASE_TOKEN --platforms=android --yes
      - name: Build APK
        working-directory: ./habitflow
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: habitflow/build/app/outputs/flutter-apk/app-release.apk